kind: ConfigMap
apiVersion: v1
metadata:
  name: tcp-services
  namespace: ingress-nginx
data:
  3306: "kube-devops/devopsphere-mysql:3306"
  2379: "kube-devops/devopsphere-etcd:2379"
  6379: "kube-devops/redis-ha-redis-ha-master-svc:6379"