### CreateTemplate
POST http://localhost:8001/api/v1alpha1/templates HTTP/1.1
Authorization: Basic admin admin
Content-Type: application/json

{
    "name":"ruby23",
    "description_en":"Ruby is a dynamic, reflective, object-oriented, general-purpose, open-source programming language",
    "description_zh":"将Ruby应用一步打包成镜像",
    "icon_path":"",
    "builder_image":"centos/ruby-23-centos7",
    "status":"beta",
    "language":"ruby",
    "fields":[
        {
            "name":"Source",
            "tips_zh":"代码仓库地址，目前支持git和http/https开头的仓库地址",
            "tips_en":"url of source code, currently only git and http/https are supported",
            "field_type":"text",
            "constraints":"URL"
        },
        {
            "name":"RUBYGEM_MIRROR",
            "tips_zh":"rubygem的镜像地址，为了节省流量，这里会设置成集群中的变量",
            "tips_en":"Set this variable to use a custom RubyGems mirror URL to download required gem packages during build process.",
            "field_type":"text,environment",
            "default_value":"http://nexus.kubesphere.com/repository/internal_gem/",
            "constraints":"URL"    
        }
    ]
}

### Get Templates
GET  http://localhost:8001/api/v1alpha1/templates HTTP/1.1
Authorization: Basic admin admins